<?php

declare(strict_types=1);
require_once __DIR__ . '/../includes/layout.php';
if (!app_installed()) redirect('install.php');
require_admin();
if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf();$id=(int)($_POST['question_id']??0);$status=(string)($_POST['status']??'');$answer=trim((string)($_POST['answer_text']??''));$published=!empty($_POST['published'])?1:0;$allowed=['open','waiting','taken','answered','archived'];if(in_array($status,$allowed,true)){$waiting=$status==='waiting'?'COALESCE(waiting_since,NOW())':'waiting_since';$answered=$status==='answered'?'COALESCE(answered_at,NOW())':'answered_at';$sql="UPDATE questions SET status=?,answer_text=?,published=?,waiting_since={$waiting},answered_at={$answered} WHERE id=?";$stmt=db()->prepare($sql);$stmt->execute([$status,$answer!==''?$answer:null,$published,$id]);flash('success','Pergunta atualizada.');}redirect('admin/questions.php');}
$questions=db()->query('SELECT q.*,u.name author_name,(SELECT COUNT(*) FROM question_votes v WHERE v.question_id=q.id) votes FROM questions q JOIN users u ON u.id=q.user_id ORDER BY q.created_at DESC')->fetchAll();
render_header('Perguntas',true);
?><section class="admin-head"><div><div class="eyebrow">PERGUNTAS</div><h1>Moderação e respostas</h1><p class="muted">Mude o estágio, registre uma resposta e controle o cronômetro do silêncio.</p></div></section><div class="admin-question-list"><?php foreach($questions as $q):?><form method="post" class="panel question-admin"><?=csrf_field()?><input type="hidden" name="question_id" value="<?=$q['id']?>"><div class="panel-head"><div><span class="category"><?=h($q['focus_name'])?> · <?=h($q['category'])?></span><h2><?=h($q['title'])?></h2><div class="muted">por <?=h($q['author_name'])?> · <?=$q['votes']?> endosso(s)</div></div><a class="button ghost small" href="<?=h(base_url('question.php?id='.$q['id']))?>">Abrir</a></div><div class="form-row"><label>Status<select name="status"><?php foreach(['open'=>'Aberta','waiting'=>'Aguardando resposta','taken'=>'Pauta assumida','answered'=>'Resposta registrada','archived'=>'Arquivada'] as $value=>$label):?><option value="<?=$value?>" <?=$q['status']===$value?'selected':''?>><?=$label?></option><?php endforeach;?></select></label><label>Resposta<textarea name="answer_text" rows="4" placeholder="Registre aqui a resposta oficial ou o resumo documentado."><?=h($q['answer_text'])?></textarea></label></div><label class="checkbox"><input type="checkbox" name="published" value="1" <?= $q['published'] ? 'checked' : '' ?>> Publicada no site</label><button class="button primary small" type="submit">Salvar alterações</button></form><?php endforeach;?></div><?php render_footer();?>
