<?php

declare(strict_types=1);
require_once __DIR__ . '/../includes/layout.php';
if (!app_installed()) redirect('install.php');
$admin=require_admin();
if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf();$id=(int)($_POST['user_id']??0);$action=(string)($_POST['action']??'');if($id===(int)$admin['id']){flash('warning','Você não pode desativar ou remover seu próprio acesso administrativo aqui.');redirect('admin/users.php');}$stmt=db()->prepare('SELECT id,role,active FROM users WHERE id=?');$stmt->execute([$id]);$target=$stmt->fetch();if($target){if($action==='toggle_active'){$s=db()->prepare('UPDATE users SET active=? WHERE id=?');$s->execute([(int)!((int)$target['active']),$id]);}elseif($action==='toggle_role'){$role=$target['role']==='admin'?'user':'admin';$s=db()->prepare('UPDATE users SET role=? WHERE id=?');$s->execute([$role,$id]);}}redirect('admin/users.php');}
$users=db()->query('SELECT id,name,email,role,active,created_at FROM users ORDER BY created_at DESC')->fetchAll();
render_header('Usuários',true);
?><section class="admin-head"><div><div class="eyebrow">USUÁRIOS</div><h1>Contas e permissões</h1><p class="muted">Ative, desative e promova usuários. Autocadastro sempre cria perfil comum.</p></div></section><section class="panel"><div class="table-wrap"><table><thead><tr><th>Usuário</th><th>Perfil</th><th>Status</th><th>Cadastro</th><th>Ações</th></tr></thead><tbody><?php foreach($users as $u):?><tr><td><strong><?=h($u['name'])?></strong><br><span class="muted"><?=h($u['email'])?></span></td><td><?=h($u['role'])?></td><td><?=$u['active']?'Ativo':'Desativado'?></td><td><?=date('d/m/Y',strtotime($u['created_at']))?></td><td><?php if((int)$u['id']!==(int)$admin['id']):?><div class="inline-actions"><form method="post"><?=csrf_field()?><input type="hidden" name="user_id" value="<?=$u['id']?>"><input type="hidden" name="action" value="toggle_role"><button class="button ghost small" type="submit"><?=$u['role']==='admin'?'Tornar usuário':'Tornar admin'?></button></form><form method="post"><?=csrf_field()?><input type="hidden" name="user_id" value="<?=$u['id']?>"><input type="hidden" name="action" value="toggle_active"><button class="button ghost small" type="submit"><?=$u['active']?'Desativar':'Ativar'?></button></form></div><?php else:?><span class="muted">Sua conta</span><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></section><?php render_footer();?>
